# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build TEST

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' && github.event.repository.default_branch == 'master' }}

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine32 wine -y
    - run: yarn --frozen-lockfile
    - run: yarn build:win
    - run: echo "${{ github.ref }}"
    - run: echo "${{ secrets.GPA }}"
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GPA }}
      with:
        tag_name: ${{ github.event.tag }}
        files: |
          dist/*
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./dist
        retention-days: 1
